name: Print CIAO

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  print-ciao:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Print CIAO
        env:
          CIAO: ${{ vars.CIAO }}
        run: echo "$CIAO"
