name: Print Custom Config JSON

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  print-custom-config:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - name: Print CUSTOM_CONFIG_JSON
        env:
          CUSTOM_CONFIG_JSON: ${{ vars.CUSTOM_CONFIG_JSON }}
        run: echo "$CUSTOM_CONFIG_JSON"
